fix the inline issue in the featured Posts of skeleton ui across all devices
krishnaacharyaa/wanderlust pull request #111
Opened 2024-03-25 14:03 UTC by SohamRoy-01

## Summary

Close the issue [BUG] Featured posts card is not inline with the skeleton card (shimmer card) #109

## Description

fix the inline issue in the featured Posts of skeleton ui across all devices

## Video

https://github.com/krishnaacharyaa/wanderlust/assets/104237973/b9094ec4-75a3-4833-99b0-efe4beacfcf6

2024-03-26 02:42 UTC, krishnaacharyaa requested changes
Thank you for the PR, Kindly follow contributing guidelines. and Address the review

2024-03-26 02:42 UTC, krishnaacharyaa commented on frontend/src/components/skeletons/featured-post-card-skeleton.tsx
Why have we changed this? 
Please don't change the entire code, only the required places to be change, and keep it as minimal as possible the changes. For some reason I am guessing this is taken out from the chatgpt...

And the height of the image and the whole card is not aligned in the desktop mode,
And the description needs to be of higher height is what is seems, Please refresh the page and check if they exactly align?

2024-03-27 17:19 UTC, SohamRoy-01 commented
Hey @krishnaacharyaa, the project is nearly complete. Apologies for the delay, I've been occupied for the past couple of days. I'll ensure to update the pull request (PR) tomorrow.

2024-03-27 18:44 UTC, krishnaacharyaa commented
Thank you for the quick update, please resolve the merge conflicts (It is because in the previous PR the classnames were reordered nothing else)... And just one thing to add here is ... the height of the description when its mobile screen is greater than the actual description height ....

Can you kindly fix these 2, will merge the PR

2024-03-27 20:20 UTC, closed without merging