feat: Added redis for caching the posts data
krishnaacharyaa/wanderlust pull request #136
Opened 2024-04-09 06:20 UTC by krishnaacharyaa

## Summary

The loading of the posts is taking nearly 5s to get from the server, which is quite huge, so added a redis layer on top of it, so that the posts data is cached initially and when the new posts is added it is invalidated.

## Description

It is aimed to bring down the latency of the fetch call from the backend server. Now it is taking nearly 5sec without redis for all the fetches.

### NOTE !!
You would have to set a redis in your local machine or create a redis account in the [upstash](https://console.upstash.com/redis) and place the generated url in the .env `REDIS_URL`'s value

## Images
Before Redis
<img width="1079" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/d2dfd784-fac8-4c6f-afa9-8a2dceb03217">

## Prerequisites

[-] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2024-04-09 08:50 UTC, chinmaykunkikar commented
![image](https://github.com/krishnaacharyaa/wanderlust/assets/6230769/9628ee90-06b0-427c-8a47-793a82bd7973)
The api request URL is bad here

2024-04-09 09:06 UTC, krishnaacharyaa commented
> ![image](https://private-user-images.githubusercontent.com/6230769/320783953-9628ee90-06b0-427c-8a47-793a82bd7973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM1NjEsIm5iZiI6MTcxMjY1MzI2MSwicGF0aCI6Ii82MjMwNzY5LzMyMDc4Mzk1My05NjI4ZWU5MC0wNmIwLTQyN2MtOGE0Ny03OTNhODJiZDc5NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDkwMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Y1MDkxYTFiMmUwZWM1NTcyMTFiZDU4YTI2YzVhZDNjN2E2ZDY0NGIxN2Q5NWJjMmJlMDNjODZkYmRiYTEwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ymF5xf4ePOhRbRrSX93_GyJsOsFxMC_fgXMNSw93ZGo) The api request URL is bad here

Where exactly did you hit this? I am playing around with CORS, and quite a few changes in the endpoints and to whitelist and stuff...
Production app is now down. 

<img width="473" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/f2f3c97a-f001-4086-bd7b-1087b0075f16">
This has recently slipped in the production, causing all the issue, in production if I give proper CORS_URL works as expected.
But in preview deployments as every deployment name changes, it causes deadlock, 
Frontend needs VITE_URL from backend
Backend needs this CORS_URL of frontend... basically causing a deadlock. In production it is fine though... because the domain name doesn't change, 

Any take on this? I have removed this CORS_URL change and trying to make it work, production app is now down, not sure how it was running previously :)

2024-04-11 03:33 UTC, krishnaacharyaa commented
@chinmaykunkikar @bajajcodes  Need your reviews

2024-04-11 11:47 UTC, krishnaacharyaa commented
Succesfully cross checked in local, working just fine as expected and checked with the remote redis cache aswell

2024-04-11 21:28 UTC, bajajcodes requested changes
Better put redis under a services, and use single client, and connect to redis at the start of the server.

2024-04-11 21:28 UTC, bajajcodes commented on backend/utils/cache-posts.js
> +export async function getKeyFromCache(key) {
Better to use `retrieveDataFromCache`, and `storeDataInCache`

2024-04-11 21:28 UTC, bajajcodes commented on backend/utils/cache-posts.js
> +export async function getKeyFromCache(key) {
[OPTIONAL]: You can create a single service which will take care of redis connection, redis client and supporting methods/features.

2024-04-11 21:28 UTC, bajajcodes commented on backend/config/redis.js
> +import dotenv from 'dotenv';
configs are not used for clients, better to use service for redis client.
To get environment-vars, you can use config.

2024-04-11 21:28 UTC, bajajcodes commented on backend/config/redis.js
> +  console.log('Redis not configured, cache disabled.');
If env is missing throw error or return null.

2024-04-11 21:28 UTC, bajajcodes commented on backend/utils/cache-posts.js
> +export async function invalidateKeyInCache(key) {
Alternative name: deleteKeyFromCache

2024-04-13 20:22 UTC, krishnaacharyaa commented
All the comments are addressed, Ek aur baar review kardeejiye please :)

2024-04-14 07:28 UTC, merged