feat-#146: Added Admin UI Screens to Frontend
krishnaacharyaa/wanderlust pull request #155
Opened 2024-04-17 19:06 UTC by devsharmagit

## Summary

This PR adds the admin UI screens to the frontend

## Description

Admin UI screens are added to the frontend with responsive and mobile optimization.
/admin/users /admin/blogs are the routes

## Images

![image](https://github.com/krishnaacharyaa/wanderlust/assets/109821078/0a1e8ac9-ec1e-41f8-b659-77074df3f7a8)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/109821078/7b1cf21b-5fe4-40f0-83eb-af84d2a43753)

## Issue(s) Addressed

Closes: #146 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2024-04-18 02:34 UTC, krishnaacharyaa commented
Please run `npm run format` in the frontend directory,
Please make sure it is dark mode proof, if it seems to take time create a new story for the same.
<img width="1204" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/e9b557d8-7417-4909-a04d-3ed80dea9834">

Take care of this error in the deployment :)

Thank you for the PR, looks very neat !!

2024-04-18 03:09 UTC, devsharmagit commented
I will solve this error and add dark mode styles as well.
I will submit it tonight.
do I just have to commit to this branch and raise another pr?

2024-04-21 15:27 UTC, krishnaacharyaa commented
@devsharmagit please fix the build issues as mentioned above so that we can merge this

2024-04-22 18:11 UTC, devsharmagit commented
@krishnaacharyaa 
I have committed to the dark mode functionality.
check and let me know if everything is all right or not?

2024-04-22 19:00 UTC, krishnaacharyaa requested changes
Looks clean to me, if possible kindly take care of the mobile screen, it would be a good challenge and makes you perfect in tailwind.

2024-04-25 03:21 UTC, krishnaacharyaa requested changes
Thank you for the quick response, couple of reviews if you could address them

2024-04-25 03:21 UTC, krishnaacharyaa commented on frontend/src/components/admin-sidebar.tsx
> +
Shouldn't this be false by default?

2024-04-25 03:21 UTC, krishnaacharyaa commented on frontend/src/components/admin-container.tsx
I guess we are not using this component. But lets use this in my opinion.

2024-04-25 03:21 UTC, krishnaacharyaa commented on frontend/src/pages/admin-blogs.tsx
> +        <div className="w-full p-3 px-5 md:p-12">
Adding AdminSidebar in all the blogs will be redundant and not a good practice. So we would be needing the wrapper

2024-04-25 03:21 UTC, krishnaacharyaa commented on frontend/src/App.tsx
> +              <Route path="users" element={<AdminUsers />} />
This is good, similarly do we have a hack to eliminate the wrapper in the `app.tsx`? Would be a good one if we could get it, else we'll use the wrapper AdminContainer

2024-04-28 05:42 UTC, krishnaacharyaa commented
Hi @devsharmagit, by when can we close this?

2024-04-28 07:13 UTC, devsharmagit commented
@krishnaacharyaa 
just commited the changes

2024-04-28 10:14 UTC, krishnaacharyaa approved these changes
Thank you @devsharmagit, LGTM. Merging right away :)

2024-04-28 10:14 UTC, merged