fix-#257: Hide and visible in password to improve UI
krishnaacharyaa/wanderlust pull request #299
Opened 2024-05-19 13:08 UTC by GOURAVSINGH19

## Summary

I improve the sign in and signup page by adding visible and hide password feature which help use to check the password before submit...

https://github.com/krishnaacharyaa/wanderlust/assets/120244528/eb167125-fe64-4de0-8ed5-846aac91aade

2024-05-19 13:21 UTC, krishnaacharyaa requested changes
Kindly use the standard svg icons from flaticon

2024-05-19 13:21 UTC, krishnaacharyaa commented on frontend/package-lock.json
Why is there a new package-lock.json?

2024-05-19 13:21 UTC, krishnaacharyaa commented on frontend/src/pages/signin-page.tsx
> +                  xmlns="http://www.w3.org/2000/svg"
kindly take this svg out and put it in assets and import like the other svgs being used in the project

2024-05-19 13:21 UTC, krishnaacharyaa commented on frontend/src/pages/signup-page.tsx
> +                  xmlns="http://www.w3.org/2000/svg"
Same comment

2024-05-19 13:21 UTC, krishnaacharyaa commented on package-lock.json
Why is there a new package-lock.json?

2024-05-19 13:24 UTC, GOURAVSINGH19 commented on package-lock.json
give a time I will fix it

2024-05-19 13:26 UTC, krishnaacharyaa commented
Kindly rebase the branch to latest branch, worflow file has some changes, so that is causing this fail in PR title checking job

2024-05-19 14:39 UTC, GOURAVSINGH19 commented
I donot know by it cannot merge..

2024-05-19 14:54 UTC, krishnaacharyaa requested changes

2024-05-19 14:54 UTC, krishnaacharyaa commented on frontend/src/assets/svg/link.svg
Why have you touched this?

2024-05-19 14:54 UTC, krishnaacharyaa commented on frontend/src/pages/signup-page.tsx
> -              <p className="p-3 text-xs text-red-500">{errors.fullName.message}</p>
Why this is changed?

2024-05-19 14:56 UTC, krishnaacharyaa commented
Forget about the PR title check , i'll take care of it.
@GOURAVSINGH19 kindly update what are the icons you have used and don't touch any other files other than what is required

2024-05-20 17:14 UTC, krishnaacharyaa commented
@GOURAVSINGH19 kindly address the review comments

2024-05-20 17:22 UTC, GOURAVSINGH19 commented on frontend/src/pages/signup-page.tsx
> -              <p className="p-3 text-xs text-red-500">{errors.fullName.message}</p>
I already fix it

2024-05-22 04:15 UTC, krishnaacharyaa commented
@GOURAVSINGH19 please change the icons, and don't touch any other icon or update other files, and once all this is done, update the PR description to reflect those icons

2024-05-24 17:49 UTC, closed without merging