refactor-#418: Added role type in frontend and backend
krishnaacharyaa/wanderlust pull request #422
Opened 2024-06-18 15:04 UTC by AMS003010

## Summary

I have added the role type (as an enum) in both the backend and frontend and replaced the "USER" and "ADMIN" types with `Role.User` and `Role.Admin`

## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

## Images

None

## Issue(s) Addressed

Closes [Issue #418](https://github.com/krishnaacharyaa/wanderlust/issues/418)

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2024-06-18 15:14 UTC, krishnaacharyaa requested changes
<img width="505" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/f85d1f31-fe18-422c-b22d-48ab200523a3">

I see "ADMIN" being used in 6 files, but only 4 are touched.

<img width="508" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/bbae91f0-b3d8-4478-92b3-56c2a098592a">
And "USER" being used in 4 files, only 3 are touched,

Kindly make sure everything is covered before raising PR, else we have to cross check this way :)

2024-06-18 15:18 UTC, krishnaacharyaa requested changes
Kindly make sure if the application is completely running without errors, because i straight away see, compilation issue. Didn't it catch while linting? If not kindly let me know... while commit it should ideally run the eslint --fix . and give errors, not sure how this slided from there

2024-06-18 15:18 UTC, krishnaacharyaa commented on backend/middlewares/auth-middleware.js
Are you sure this is not giving any compilation issues? role-type i see is of tsx and here it is imported as js

2024-06-18 15:18 UTC, krishnaacharyaa commented on backend/controllers/user-controller.js
same comment as below one

2024-06-19 03:52 UTC, krishnaacharyaa commented
Hi @AMS003010 can you kindly address the review comments and close this by today?

2024-06-19 15:37 UTC, krishnaacharyaa commented on backend/types/role-type.tsx
I still doubt if this is working, because the backend is not still not ts compatible, how where you able to define tsx? 
Did it compile succesfully? It ideally shouldn't @AMS003010 .
Or you might have just refactored and didn't actually run the application. Correct? 

I'm confused how the builds are passing !!

2024-06-19 18:50 UTC, AMS003010 commented on backend/types/role-type.tsx
Yeah I actually didn't run the application 😅

2024-06-19 18:50 UTC, AMS003010 commented on backend/types/role-type.tsx
Let me just see...

2024-06-20 03:24 UTC, krishnaacharyaa commented
> Yeah I actually didn't run the application 😅

@AMS003010 kindly run the application and push the required changes

2024-06-20 04:03 UTC, krishnaacharyaa commented
@AMS003010 did you run the application?

2024-06-20 12:12 UTC, krishnaacharyaa commented
@AMS003010

2024-06-20 12:14 UTC, AMS003010 commented
Yeah i did
It worked without any errors

2024-06-20 12:18 UTC, krishnaacharyaa approved these changes
LGTM, thank you

2024-06-20 12:18 UTC, merged

2024-06-20 12:21 UTC, AMS003010 commented
@krishnaacharyaa Thanks a lot for the help 😁