feat-#429: Added Signin with Google button
krishnaacharyaa/wanderlust pull request #454
Opened 2024-07-20 13:30 UTC by siddharthisrani

Summary
This PR introduces the 'Sign in with Google' button to the login page, enabling users to authenticate using their Google accounts.

Description
This PR addresses the need for Google authentication within the WanderLust application. The changes include:

   Addition of 'Sign in with Google' Button:
    Implemented a new button on the login page to initiate Google sign-in.

   Google OAuth2 Strategy Integration:
    Integrated Passport.js with the Google OAuth2 strategy for handling authentication.

  Google OAuth2 Configuration:  
    Configured the application to use Google OAuth2 credentials (client ID and secret) via environment variables.

  OAuth2 Callback Handling:
     Implemented the logic to handle the Google OAuth2 callback, authenticate users, and create user sessions.

  Frontend UI Update:
     Updated the frontend to display 'Create Post' and 'Logout' buttons upon successful Google login.

Technical details:
   The Google OAuth2 client ID and secret are securely managed through environment variables.
   Passport.js is used to manage the Google authentication strategy.
   The frontend dynamically updates to reflect the user's authenticated state.

Issue(s) Addressed
Closes #429

Prerequisites
 Yes followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2024-07-20 19:32 UTC, krishnaacharyaa commented
Please attach a video of a working demo

2024-07-20 19:32 UTC, krishnaacharyaa commented
@Sukomal07 can you please review

2024-07-20 19:32 UTC, krishnaacharyaa commented
@Deblin798 feel free to review

2024-07-21 08:16 UTC, siddharthisrani commented
> Please attach a video of a working demo


https://github.com/user-attachments/assets/c703c1e3-7723-4f36-90c8-b481ddb8f438

2024-07-21 13:23 UTC, krishnaacharyaa requested changes
Thank you for the PR @siddharthisrani 
Just couple of review comments, kindly address
And if any env variables are used, add it in the .env.sample

2024-07-21 13:23 UTC, krishnaacharyaa commented on backend/config/passport.js
> +    },
As we are deploying in vercel, we can't hardcode this to 8080, kindly move this to evn variable or in this case i guess you need to use the backend_url env variable

2024-07-21 13:23 UTC, krishnaacharyaa commented on backend/routes/auth.js
> +  }
Same here, kindly use frontend url env variable

2024-07-21 13:23 UTC, krishnaacharyaa commented on frontend/src/pages/signup-page.tsx
> +  };
Same here

2024-07-21 13:23 UTC, krishnaacharyaa commented on frontend/src/pages/signup-page.tsx
> +          if (user && user._id && user.role) {
localstorage we are setting token not in the cookies? @Sukomal07 kindly confirm

2024-07-21 15:26 UTC, siddharthisrani commented
Hii @krishnaacharyaa the requested changes to use environment variables for URLs in Google OAuth and redirects 

Changes Made:
Used environment variables for URLs in Google OAuth and redirects.
Updated .env.sample to include the new environment variables.

2024-07-23 06:31 UTC, krishnaacharyaa commented
@Sukomal07 can you please have a look at this PR

2024-07-23 06:55 UTC, Sukomal07 commented
> @Sukomal07 can you please have a look at this PR

@siddharthisrani didn't reply to my question.

2024-07-23 06:59 UTC, krishnaacharyaa commented
@siddharthisrani please sync up with @Sukomal07 , so that we can merge this

2024-07-23 07:58 UTC, siddharthisrani commented
> @siddharthisrani didn't reply to my question.
Hi @Sukomal07  and @krishnaacharyaa ,

Regarding the question about token storage:

In the current implementation, the token is being set in local storage after a successful Google OAuth login. This was done to maintain consistency with other parts of the application that also use local storage for token management.

However, from the backend, we are also sending the token in cookies to enhance security and manage user sessions more effectively. Here’s the relevant code:

router.get(
  '/google/callback',
  passport.authenticate('google', { failureRedirect: '/' }),
  (req, res) => {
    const token = jwt.sign({ id: req.user._id }, process.env.JWT_SECRET, { expiresIn: '1h' });
    res.cookie('access_token', token, {
      httpOnly: true,
      
![Cookie](https://github.com/user-attachments/assets/2c405b00-2f89-41c1-ae72-989e4ee0d39f)

This implementation ensures that the token is available in cookies for enhanced security, while local storage is used to maintain consistency in token management across the application.

Please let me know if my answer is according to your requirements. If any further changes needed i will be happy to assist you.

2024-07-23 08:31 UTC, siddharthisrani commented
> @siddharthisrani can we do without saving token in localstorage ?

Sure ,i will look in this part for solutions and get back to you .

2024-07-23 09:23 UTC, siddharthisrani commented
Hii @Sukomal07 
Yes, it's working well without saving the token in local storage.
![localStorage](https://github.com/user-attachments/assets/43ff7b08-992a-4d9a-ab15-6bdc42732a84)
![removedLocalStorage](https://github.com/user-attachments/assets/270a6c8d-55a1-4fcf-baf5-c4a980341ee9)

2024-07-23 10:12 UTC, Sukomal07 commented
@siddharthisrani Nice , then remove localstorage part from all of your code.

2024-07-23 11:17 UTC, siddharthisrani commented
Hii @Sukomal07,

I've removed the token saving in local storage from all the relevant parts of the code. Please review the latest commits.

2024-07-23 14:06 UTC, Sukomal07 approved these changes

2024-07-23 14:06 UTC, Sukomal07 approved these changes

2024-07-23 17:11 UTC, krishnaacharyaa approved these changes
Thank you @siddharthisrani for your active contribution

2024-07-23 17:12 UTC, merged