feat-#55: Introduced Slug Integration to Enhance URL Sharing
krishnaacharyaa/wanderlust pull request #74
Opened 2023-12-09 10:49 UTC by vishalkumar9

## Summary

**Introduced Slug Integration to Enhance URL Shari*ng.**

## Description

### Problem
User not able to see post using shared URLs.

### What Cause This Problem?

In details-page
const {state} = useLoaction();
This line of code uses destructuring to extract the state property from the object returned by the useLocation hook. The state property contains any state data that was passed along with the navigation.
The state passed via location.state in React Router is specific to the current session and is not maintained in the URL itself. When you navigate directly to a URL that includes a state from an external source (like a shared link), React Router won't have that state information available, and location.state will be undefined.

###Approach

We've updated our URLs to follow the format details-page/:title/:postId. This change enables us to extract the postId from the URL, allowing us to send a request to the backend and retrieve data associated with that specific postId.

We're leveraging the title in the URL to enhance readability for users. When users access a post directly from the website, we utilize the location.state property to retrieve the data linked to that particular post.

## Images

![Screenshot (42)](https://github.com/krishnaacharyaa/wanderlust/assets/64836800/881eb7e1-4ceb-42ed-8f69-d9b639ea0c96)

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes #55 **
- Example: Closes #55 

## Prerequisites

- [ ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2023-12-09 10:52 UTC, vishalkumar9 commented
@krishnaacharyaa PR ready for your review—checks passed, no conflicts.

2023-12-10 04:54 UTC, krishnaacharyaa requested changes
Thank you for a very improved PR, from the previous one, really appreciated.
Kindly address the little changes and we are good to merge this

2023-12-10 04:54 UTC, krishnaacharyaa commented on frontend/src/components/featured-post-card.tsx
>    return (
Can we create a util for this, as i see it is getting used in every component, it would be better if we could reuse the function.

2023-12-10 04:54 UTC, krishnaacharyaa commented on frontend/src/components/latest-post-card.tsx
>    return (
Same here

2023-12-10 04:54 UTC, krishnaacharyaa commented on frontend/src/components/post-card.tsx
>    return (
And here

2023-12-10 04:54 UTC, krishnaacharyaa commented on frontend/src/pages/details-page.tsx
>  import formatPostTime from '@/utils/format-post-time';
Can we remove this comment, if this is not needed?

2023-12-10 04:54 UTC, krishnaacharyaa commented on frontend/src/pages/details-page.tsx
>      <div className="min-h-screen bg-light dark:bg-dark">
Kindly run the npm run format on the frontend, so that the code is readable and formatted nicely.

2023-12-10 04:56 UTC, krishnaacharyaa commented
@vishalkumar9, just a couple of things in the PR description, you need to tick, "have you follow the community guidelines" and the issue addressed section should have only one issue, you should remove the example part, you can refer to the merged PRs

2023-12-10 06:15 UTC, vishalkumar9 commented
@krishnaacharyaa  I have addressed the requested changes. The code has been updated and is now ready for review and merging.

2023-12-11 11:44 UTC, krishnaacharyaa approved these changes
Thank you for the PR, LGTM

2023-12-11 11:45 UTC, merged