Fixed the indentation of "All Posts" cards.
krishnaacharyaa/wanderlust pull request #82
Opened 2023-12-14 21:51 UTC by anishsoni29

## Summary

Fixing the indentation of the All Posts with the image box.
![Screenshot 2023-12-15 at 3 18 05 AM](https://github.com/krishnaacharyaa/wanderlust/assets/96867765/163235b5-4704-4b65-a0e1-d9c669b06162)

## Description

Fixed the indentation gap by removing the extra margin and adding the gap in the "All Posts" section.

## Images

## Issue(s) Addressed

#81

2023-12-14 21:54 UTC, niikkhilsharma approved these changes

2023-12-14 21:55 UTC, niikkhilsharma approved these changes
This code works fine.

2023-12-15 03:15 UTC, krishnaacharyaa commented
Thank you @anishsoni29 for the quick PR, but there seems to be still some changes required, here we covered only the shimmers not the actual UI
<img width="651" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/239ac8a3-66c8-4300-9dac-8ab0ff61091c">

Thank you @niikkhilsharma for taking out your time for reviewing, couple of inputs 
1. The code actually doesn't look fine in all the scenario, so kindly be very sure, when you comment.
2. And it's not about "it works fine", it is the bare minimum, but the things to focus on is quality of code, is minimal change carried out, was all the changes actually required? That comes to picture.

> Co-authoured what's about this in the commit, I didn't get the point, was there any reason behind?

2023-12-15 13:21 UTC, niikkhilsharma commented
I really appreciate your feedback. I'll try to check for more scenarios in which the code would fail.
Thanks you 😊

2023-12-15 13:23 UTC, krishnaacharyaa requested changes
Kindly address the changes, and follow the contribution guidelines 5th point staging commit

2023-12-15 13:23 UTC, krishnaacharyaa commented on frontend/src/pages/home-page.tsx
>            {posts.length === 0
Why gap-4 is added? It is breaking the UI by pushing the posts to below at the right we have empty white space now
<img width="1549" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/75a750f1-008f-4e68-bbde-c85a22e5a049">

And not exactly sure why mb-4 is added here, i understand to compensate the m-4 removal in the post-card-skeleton, but then there would be other places also to be considered

2023-12-16 18:49 UTC, krishnaacharyaa commented
#86 Fixes this issue

2023-12-16 18:49 UTC, closed without merging