tag-#77:  From validation
krishnaacharyaa/wanderlust pull request #83
Opened 2023-12-15 12:57 UTC by MrBlackGhostt

## Summary

Use the React-hook-form and Zod for the form validation

## Description

Use the React-hook-form and Zod for the form validation add validate for all the inputs and add error message for all the input

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1

## Prerequisites

- [ ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

2023-12-15 13:47 UTC, krishnaacharyaa commented
@MrBlackGhostt we know the error, kindly check the discord

2023-12-15 13:59 UTC, krishnaacharyaa requested changes
<img width="1158" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/e8af1ff5-3268-46d2-b436-19d8e02ab7e6">
Functionalities are not perfectly working.
Title though it is 3 words, The error isn't resolved,

And categories selection is broken, kindly address the comments and this, and also resolve the merge conflicts by rebasing your branch with the latest main branch

2023-12-15 13:59 UTC, krishnaacharyaa commented on frontend/src/lib/blog.zod.ts
> +  }),
We can't use "your name **should** be" emphasis on should, becuase he can be Raj, 
We can be like "C'mon your name cannot be less than 3 characters" ( if its less than 3 letters);
if greater than 15 say "Hey isn't it too big of a name, can you limit it to 15 characters" or improvise on this

2023-12-15 13:59 UTC, krishnaacharyaa commented on frontend/src/lib/blog.zod.ts
> +  }),
Nice!

2023-12-15 14:48 UTC, MrBlackGhostt commented on frontend/src/lib/blog.zod.ts
> +  }),
done the changes

2023-12-16 05:14 UTC, krishnaacharyaa commented
<img width="1173" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/9a065f2c-7eca-4b87-8072-2f0fb6a62175">
<img width="1195" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/104eb590-5397-448f-9c25-1db4852452eb">

Observations.
1. Categories selection is broken, selection is shown only after the button is cilcked
2. If you give everything right at the first go it doesn't let you create post, and doesn't even compliant
3. The dynamic error handling for the images and categories isn't worknig
4. Typo in "C'ome on! Your name cannot be less than 3 characters."
5. There are conflicts with the main branch, kindly rebase.

Request review once all of these is handled, if you feel this is too much of a task, seek help from others in the community discord,
Thank you.

2023-12-17 05:28 UTC, MrBlackGhostt commented on frontend/src/lib/blog.zod.ts
> +  }),
now I see the Sarcism here 😅

2023-12-17 16:24 UTC, krishnaacharyaa commented
If we are not working on this anymore, kindly close this

2023-12-22 11:08 UTC, closed without merging