theme-toggle-button
krishnaacharyaa/wanderlust pull request #95
Opened 2024-01-01 11:11 UTC by Raghunandan-29

## Summary

_Briefly describe the purpose of this PR._
This PR  resolves issue#36
## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._
This PR has the code for the Theme-toggle-button
## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_
This resolves the issue 36

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1
Closes#36
## Prerequisites

- [ ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?
Yes

2024-01-02 02:03 UTC, krishnaacharyaa commented
Hi @Raghunandan-29 , thank you for the PR, LGTM. Just couple of suggestions.
Can we aim the css to be like this
![IMG_20240102_073026](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/75065391-b202-4cde-973c-b08e4ae5da67)
And kindly follow all the Community guidelines and PR template page as discussed in the discord to make it eligible candidate for merging...

2024-01-02 08:59 UTC, Raghunandan-29 commented
Sure, I will change the CSS and also follow the Community guidelines

2024-01-09 09:53 UTC, krishnaacharyaa commented
Can you kindly push the changes @Raghunandan-29 which is posted in the discord

2024-01-11 11:55 UTC, krishnaacharyaa requested changes
Thank you @Raghunandan-29 for this amazing much needed PR, end functionality wise looks cool, but we also aim for code quality, which is presently not satisfying, kindly address the comments, and please follow the comunity guidelines, 
1, 2,3, 4, 5was not followed, is what I observed, 
Looking forward for the upcoming commits :)

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/App.tsx
> +          <Route index element={<HomePage />}/>
Can you kindly run `npm run format` in the frontend directory, because it helps in readability

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/components/skeletons/ScrollTop.tsx
kindly rename to `scroll-to-top.tsx`, as mentioned in the 4th point of [contributing guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/cfeab89861b81827361a115adb339f628e24abe6/.github/CONTRIBUTING.md#guidelines-for-contributions).
And why is it inside the skeletons directory?

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/components/theme-toggle.tsx
I feel `theme-toggle-button` would be a better naming for this

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/components/theme-toggle.tsx
> +            <span className="theme__icon-part"></span>
Can we kindly optimize this, doesn't look nice... code wise, can we work on this and see if we can use just tailwind-css for this and not use plain-css

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/components/theme-toggle.tsx
> +          {/* <span className="theme__fill"></span>   */}
Why are we having this commented line?

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/index.css
`index.css`, lets try to not use this, and replace it with tailwind-css, if it is not possible at all, as a last resort lets go with this, then we might have to rename this specific to the toggle-button so it would be more readable.

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/pages/add-blog.tsx
I see there are lots of commented code, kindly delete them, and keep only the required comments, tbh comments are actually not required, in a first look seems like you have directly copy pasted from chat-gpt, i may be wrong, but for the first honest opinion it looks that way :)

2024-01-11 11:55 UTC, krishnaacharyaa commented on frontend/src/pages/home-page.tsx
> +             <svg className="h-8 w-8 text-white"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  strokeWidth="2"  strokeLinecap="round"  strokeLinejoin="round">  <rect x="3" y="3" width="18
Kindly take this out as a svg component and place it where all the svgs are placed and then pull it as a component

2024-01-11 12:13 UTC, Raghunandan-29 commented on frontend/src/components/skeletons/ScrollTop.tsx
could you please suggest me that in which directory scroll-to-top.tsx should present

2024-01-11 13:18 UTC, krishnaacharyaa commented on frontend/src/components/skeletons/ScrollTop.tsx
For now you can have it in the components folder

2024-01-13 17:37 UTC, krishnaacharyaa commented
@Raghunandan-29 updates please

2024-01-13 18:16 UTC, Raghunandan-29 commented
Sorry krishna, I accidentally changes the path of skeleton.tsx, I will fix this

2024-01-14 05:57 UTC, krishnaacharyaa reviewed
Hey @Raghunandan-29, thank you for the quick update and sincere considerations of the comments and working on it. 
Sorry but still the community guidelines of PR title and commit regex is not followed, hopefully you'll pick that up in the next one, apart from that no complaints, the quality is improved 200% from the previous one and this is the very quality we are aiming for.
Thank you @Raghunandan-29 

Just a small observation here when i saw the deployment, when you are in the dark mode and come back to home page from details or add page, you see the default is sun and then it switches to the dark, for a millisecond that happens, can you look into it? 
It might be a little challenging, you might have to play with react hooks in a better way, but would be a great learning, can you pick this one part in this PR then we can close, or if you want to take it in the another PR, we'll take it, I am totally okay with that :)

2024-01-14 06:27 UTC, Raghunandan-29 commented
Thanks Krishna! and for that bug I would like to work with new PR so, I will raise new issue for this and work on it. Hope it is okay with you.

2024-01-14 06:47 UTC, krishnaacharyaa commented
Please share the created link of the issue here, so that we can merge this PR

2024-01-14 07:10 UTC, Raghunandan-29 commented
Issue link  https://github.com/krishnaacharyaa/wanderlust/issues/98#issue-2080611452

2024-01-14 07:21 UTC, krishnaacharyaa approved these changes
Thank you @Raghunandan-29, LGTM merging now

2024-01-14 07:25 UTC, merged